name: Add Contributors

on:
  issue_comment:
    types:
      - created

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request && contains(github.event.comment.body, '@all-contributors') }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run all-contributors bot
        uses: all-contributors/action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  add-contributors-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '@all-contributors') }}
    
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
          
      - name: Run all-contributors bot
        uses: all-contributors/action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
